### ISSUE TITLE
GDT but in AT&T?

### ISSUE THREAD

**Issue by Menotdan** [cfenollosa/os-tutorial#125]
I am trying to rewrite the GDT using AT&T syntax, does anyone have any tips?
Right now I'm stuck on a problem where 
```asm
.word 0xffff 
```
causes the OS to crash, and qemu reboots.
I have the code I am using here: https://github.com/Menotdan/DripOS/blob/dev/boot.s
The line in question is line 92

**Comment by jlagarespo** [comment]
#### Are you placing data in the code segment?

Be aware that you are linking for an elf executable(so that grub2 can load it) not a raw binary file that's copied to memory by the BIOS.
In the ELF format, data is placed in the data segment and code in the code one, by trying to put raw data in the code segment and taking the address of it(and passing to to lgdt), the CPU reads the GDT at the offset of your GDT in the actual loaded data segment, which porbably points to a memory location where there is just garbage data... that might be the cause of the crash.
The funny thing is that you have the data and read-only data segments in your linker script, and yet you're not using any of them (Well nvm, I guess C code uses them)

Put the GDT in the data segment(or even better in the rodata segment, because the GDT shouldn't be ever modified) and it *should* in theory work.

**Comment by jlagarespo** [comment]
Side note: you're currently using multiboot to boot your system, I would recommend you upgrade to [multiboot2](https://www.gnu.org/software/grub/manual/multiboot2/multiboot.html), because multiboot is now deprecated. Don't worry, its not very different from the original multiboot.

**Comment by Menotdan** [comment]
@jlagarespo Yeah that makes sense. I have managed to make the kernel load, but now its throwing a bunch of General fault protection exceptions when the kernel calls isr_install()

**Comment by jlagarespo** [comment]
Well, that's a completely different issue. Not sure why its happening, but are you ABSOLUTELY sure that it dies when calling isr_install()? Or rather when an interrupt happens?

**Comment by jlagarespo** [comment]
Funnily enough I'm working on interrupts right now on my kernel

**Comment by Menotdan** [comment]
@jlagarespo Yeah I Commented the whole init process out, and uncommented each line one by one and it started spitting out errors when I uncommented the isr_install();

**Comment by jlagarespo** [comment]
That doesn't prove that the fault is happening at isr_install.
The most likely thing here is that interrupt handlers are badly written and isr_install makes interrupts work with your handlers. Try debugging to see what's the exact problem.

**Comment by Menotdan** [comment]
Hmmm well, it might be that because it spits out exceptions pretty fast. I checked your OS and it seems interrupt 0x20 is called a lot? What does that one do?

**Comment by Menotdan** [comment]
Also, my OS is using this tutorial as a base, but it has expanded quite a bit, it even has a working disk driver and a discord server with a few active members. I havent changed the isr and idt code much, so I don't know what's wrong. The only thing I changed between when it worked and now is that I've moved to GRUB.

**Comment by jlagarespo** [comment]
Interrupt 0x20? The timer, what else.
Honestly i don't really know why moving to GRUB would've damaged that, but just try to setup all data structures by yourself and you should be fine.

**Comment by jlagarespo** [comment]
(by the way my VGA driver is just a copypaste of the one in this tutorial, because I was to lazy to write one myself, but I'll *maybe* do that in the future because I'll need it)

**Comment by jlagarespo** [comment]
Also, can this issue e considered closed?

**Comment by Menotdan** [comment]
hmm yeah i wonder why moving to grub changed it
im gonna close it
