### ISSUE TITLE
Actually booting

### ISSUE THREAD

**Issue by korochun** [cfenollosa/os-tutorial#129]
I know there are 2 issues and a wiki page on this topic already, but I think, that the question hasn't really been answered. Here it goes:

How to boot?

I want a real OS, not an emulated one and "use GRUB" just throws the whole tutorial out of the window, as GRUB loads the OS, switches to Protected Mode and prepares the environment for you (lessons 1-10 are useless with GRUB).

**Comment by korochun** [comment]
I tried several things and one of the following **worked** (I was able to print `Hello, World!`):
1. I copied the partition table into MBR.
2. I stabilized CS:EIP by copying ~15 bytes from the Windows bootloader.

**Comment by jlagarespo** [comment]
No, don't. Just burn it to a flash drive, and pray for your BIOS to have legacy support. And if you are trying to do something serious, then use GRUB, this tutorial is just for beginners anyway, and is in no way intended to be booted on real machines (at least for what I can tell from it).

**Comment by korochun** [comment]
Burning doesn't work at all and just shows a blinking cursor. What actually fixed the issue is a working partition table (although stabilizing CS:EIP is useful, too). HOORAY! I have a working bootable bootloader. I suggest you to add some hints on attaching a partition table, as I wasted 30+ hours, trying to find out why it doesn't boot.

**Comment by jlagarespo** [comment]
As I said, booting in legacy mode is extremly unreliable, and should not be used. Also in 16-bits EIP doesn't exist. And when you boot you should always set CS to 0 and IP should already be set to 0x7c00.
Also neither I can add hints about anything on this project because I don't have write access to it, nor would I do that even if i had, it would just confuse people. The first tutorials (and I would say even the later ones) are NOT MEANT to be booted on a real machine. If you do it it's at your own risk and consequences.

**Comment by jlagarespo** [comment]
Also quick trick to null the code segment:
```x86asm
org 0x7c00
cli ; Disable interrupts
jmp 0x0000:fix_cs ; Jump to segment 0 offset fix_cs (0x7c00+fix_cs as you use the org directive)
fix_cs: nop ; Continue code
```
