### ISSUE TITLE
Command Terminated by Signal 11?

### ISSUE THREAD

**Issue by zurgeg** [cfenollosa/os-tutorial#130]
While running the code from Lesson 2 in an online compiler, I get this:

ld: warning: cannot find entry symbol _start; defaulting to 0000000008049000
Command terminated by signal 11

Can someone fix this?

**Comment by korochun** [comment]
tl;dl: Use `nasm`.

The online assembler you are using is trying to create an executable **for your system**. This is not what you want. You need a raw (binary) file, that when burned onto a drive would be **bootable**. Most online assemblers won't do that.

**Comment by jlagarespo** [comment]
@zurgeg the assembler you use doesn't matter, as long as it understands intel syntax (or at&t if you are using it). Just don't use an online assembler, as you don't have control over what happens. That signal mean segmentation fault, and it's likely a problem they have.

@korochun as long as you're targeting x86_16 for your bootloader it doesn't matter what format you use when assembling, as you likely choose that when linking later (that's the problem he's having, with the linker, not the assembler).

Because this tutorial is meant for begginers, it's just assembling to raw 16-bit code that old BIOSes will understand, which is the easiest thing you can do. I recommand @zurgeg to download and get familiar with a [linux distro](https://itsfoss.com/best-linux-beginners/) and use the same tools that are being used in this tutorial to learn. You can then move on to better and more serious ways of booting, such as writing a full-on epic efi/legacy bootloader, or even better using multiboot2 to boot your OS so that bootloaders like grub can load it.

**Comment by zurgeg** [comment]
I tried it on Ubuntu and  got 
qemu: command not found

**Comment by jlagarespo** [comment]
Well install QEMU of course. On ubuntu or debian based distributions use ``sudo apt-get install qemu``, and it should download and install it from the official software repositories of your distro.

**Comment by jlagarespo** [comment]
![Screenshot from 2019-12-04 18-01-27](https://user-images.githubusercontent.com/26935885/70163682-2b0c9c00-16c0-11ea-889c-1d8e34747ecb.png)

**Comment by zurgeg** [comment]
Setting up a new VM running linux Ubuntu. Should let me use ```nasm``` and ```qemu```

**Comment by zurgeg** [comment]
Got the VM running. Works now. Thank for the advice!

**Comment by jlagarespo** [comment]
No problem :)

**Comment by zurgeg** [comment]
VM broke again. Any way to get a working online parser or an IDE for Windows?

**Comment by jlagarespo** [comment]
What does "VM broke again" mean?

**Comment by zurgeg** [comment]
The VM stopped working, so I think it will be easier to just figure how to
get it to work.

**Comment by Menotdan** [comment]
What does it say when you try to run it?

**Comment by zurgeg** [comment]
No, the OS broke. Not the code.

**Comment by jlagarespo** [comment]
What are the syslogs? Does it have anything to do with QEMU running?

**Comment by zurgeg** [comment]
Can’t find the syslogs. Hyper-V is saying that it couldn’t connect.

**Comment by zurgeg** [comment]
I figured out my password to the VM because I was getting my password wrong. The VM is working now!
