### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by TLHorse** [cfenollosa/os-tutorial#163]
Maintained? I found that the last update of files in this repo are years ago. I want to make sure that I am not going to make a semi-produced OS.

**Comment by jlagarespo** [comment]
The information contained here is still perfectly relevant even today, and either way this is a tutorial to teach you about low-level stuff, os development and things alike, but not by any means, a step-by-step guide to make a "full-produced OS".

Just for the record, such a thing cannot exist because of the very nature of osdev. New "full-produced" operating systems only have one chance to be created, and that's when the necessities of the user require it. For ~99.999% of the things you might want to do in computer science, you can just use a distribution of Linux and GNU and you'll be absolutely fine. In other words, this tutorial is just for learning. And most people that do osdev do it for fun anyways.

**Comment by TLHorse** [comment]
Thanks for your reply @jlagarespo,

Actually I don't count on to make a really full-produced OS with GUI like OS X or Windows - seldom people have effort to make that, not to mention a step-by-step book.

But for now, this os-tutorial have not taught even to built a **basic file system** or even a **shell**, so if this tutorial didn't finish the **basic framework and foundation** of an OS, I don't think I'll spend time on it.

**Comment by jlagarespo** [comment]
The GUI has absolutely nothing to do with the operating system, whether it is "full-produced" or not. Also we probably got some confusing nomenclature here, but more than "os-tutorial" this should probably be named "kernel-tutorial". If you want a shell, you already have bash, zsh, fish, and countless others. As for file system, you probably mean that he doesn't teach how to build a basic filesystem driver, because making a filesystem from scratch is something very advanced, and this is a begginer tutorial. Doing so was (I belive) already in the plans of the author, but this repo has not been updated for very long. And either  way, I think we can't really talk about making filesystems or shells, if this doesn't even have a proper memory manager yet; but as I said, it was meant to be here, it just never got made.

Replying to the original question, because maybe I was not clear enough in the last reply, **this tutorial is currently not being worked on, even though the information contained here still is relevant today**. There is nothing wrong on getting started on this tutorial and then continuing from other places. **I strongly recommend you checkout the [osdev wiki](https://wiki.osdev.org/Main_Page)** and read specifically this pages:
* https://wiki.osdev.org/Introduction
* https://wiki.osdev.org/Beginner_Mistakes
* https://wiki.osdev.org/Required_Knowledge
* https://wiki.osdev.org/Getting_Started

**Comment by farisshajahan** [comment]
In case you are simply looking to learn operating system concepts, checkout the eXpOS project at <https://exposnitc.github.io>

**Comment by TLHorse** [comment]
@jlagarespo @farisshajahan Thanks for all your help. The osdev wiki sounds great. I'll try it. But, in a nutshell, just for fun.
