### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by BaseProgrammer** [cfenollosa/os-tutorial#198]
I opened this issue to find out if there is any tutorial on how to make a file system; on the other responses of previous, ancient issues, the GitHub links are either not working or just wrong.

Sorry I am kind of new to C-lang and wondering if I can make one; I also looked at the PDF document but there's nothing there for filesystems.

**Comment by algorithmx51** [comment]
You mean how to make a custom filesystem from scratch or use an existent format like FAT-32 or ext4?

**Comment by BaseProgrammer** [comment]
Yeah

**Comment by BaseProgrammer** [comment]
Making a custom filesystem using the ext4 format...

**Comment by algorithmx51** [comment]
To use ext4 on your filesystem, you need to know how ext2 works, because ext3 and ext4 are like patches for ext2
[Here is how ext2 works](https://wiki.osdev.org/Ext2)
[What is vfs and why you need it to handle files more easily](https://wiki.osdev.org/VFS)
[And a discussion on VFS development](https://forum.osdev.org/viewtopic.php?f=1&t=9129)
[Ext4 changes over ext2](https://wiki.osdev.org/Ext4)

[Here are some other filesystems in case you want to take a look (and some filesystem theory)](https://wiki.osdev.org/File_Systems)

But to use these formats you need a disk driver, like AHCI (where you need to have a [PCI](https://wiki.osdev.org/PCI) driver) or use ATA PIO

[AHCI](https://wiki.osdev.org/AHCI) is much faster (but harder to implement) than [ATA PIO](https://wiki.osdev.org/ATA_PIO_Mode) (easier to implement), since AHCI uses [DMA](https://wiki.osdev.org/DMA) but with ATA PIO you need to write to the system bus and read from it for every read/write to the hard disk

**Comment by BaseProgrammer** [comment]
Cool thanks a lot!
