### ISSUE TITLE
Is this still active

### ISSUE THREAD

**Issue by joneschrisan** [cfenollosa/os-tutorial#39]
Is this still active and being updated. The last commit was over 4 months ago.

**Comment by MertalpTasdelen** [comment]
I don't think so but it's helpful for me until now

**Comment by Ghifari160** [comment]
@MertalpTasdelen 
> ... until now
If you are struggling somewhere, I  might be able to help you. Don't clutter this issue though.

@joneschrisan It doesn't seem that it's active, though if @cfenollosa ever wants to update it, they just need to merge a few PRs to fix the issues with this guide

**Comment by cfenollosa** [comment]
Hi all,

You are right, the repo hasn’t had activity in a long time. Since this was a personal learning project, and I still have hopes to get into it at some point, it doesn't make sense to accept pull requests.

Please feel free to fork the repo and improve it. Hope the current content has been helpful up to this point.

I'll update the README to reflect this status.

Best,
Carlos

**Comment by cfenollosa** [comment]
If many of you are interested in continuing the project, let me know and I'll link the "main fork" from the README too!
