### ISSUE TITLE
Software license, please?

### ISSUE THREAD

**Issue by Michael-S** [cfenollosa/os-tutorial#51]
Hello, it would be nice to have a license on all of this so we know the conditions to share it.

**Comment by mbrukman** [comment]
To echo what @Michael-S said: please add an explicit `LICENSE` file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed.

Per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Thanks!

**Comment by mbrukman** [comment]
Thank you, @cfenollosa! Much appreciated.

**Comment by Michael-S** [comment]
Thank you!
